---
name: CI

on: [push]

jobs:
  build-scripts:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04, windows-latest, macos-latest]
        include:
          - os: windows-latest
            generator: VS16Win64
          - os: ubuntu-20.04
            generator: Ninja
          - os: macos-latest
            generator: Ninja
    steps:
      - name: Download Source
        uses: actions/checkout@v2

      - name: Cache Conan Packages
        uses: actions/cache@v2
        with:
          path: ~/.conan/data
          key: ${{ runner.os }}-conan-package-cache-${{ hashFiles('conanfile.txt') }}

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install CMake
        uses: lukka/get-cmake@latest

      - name: Install Conan
        run: |
          python -m pip install --upgrade pip
          pip install conan

      - name: Run CMake
        uses: lukka/run-cmake@v3
        with:
          cmakeGenerator: ${{ matrix.generator }}
          cmakeBuildType: Release

      - name: Archive Script Library
        uses: actions/upload-artifact@v2
        with:
          name: native-scripts
          path: |
            godot/bin/scripts.dll
            godot/bin/scripts.dylib
            godot/bin/scripts.so

  run-gut-tests:
    needs: build-scripts
    runs-on: ubuntu-latest
    steps:
      - name: Download Source
        uses: actions/checkout@v2
        with:
          lfs: true

      - name: Download Script Libraries
        uses: actions/download-artifact@v2
        with:
          name: native-scripts
          path: godot/bin

      - name: Run GUT Tests
        uses: croconut/godot-tester@v2
        with:
          version: 3.2.2
          path: godot
...
